# Generated by Django 3.0.4 on 2020-03-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cc', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email_from', models.CharField(blank=True, max_length=128, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('date_open', models.DateTimeField(blank=True, null=True)),
                ('date_last_stage_update', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_proposed_extra', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_expected_extra', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_proposed', models.FloatField(blank=True, null=True)),
                ('salary_expected', models.FloatField(blank=True, null=True)),
                ('availability', models.DateField(blank=True, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('partner_mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('delay_close', models.FloatField(blank=True, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('kanban_state', models.CharField(max_length=100)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'hr_applicant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrApplicantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_applicant_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrApplicantHrApplicantCategoryRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hr_applicant_hr_applicant_category_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complete_name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrDepartmentMailChannelRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hr_department_mail_channel_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrDepartureWizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_departure_wizard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('marital', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_complete_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_birthdate', models.DateField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('ssnid', models.CharField(blank=True, max_length=100, null=True)),
                ('sinid', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_id', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=100, null=True)),
                ('permit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_expire', models.DateField(blank=True, null=True)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('certificate', models.CharField(blank=True, max_length=100, null=True)),
                ('study_field', models.CharField(blank=True, max_length=100, null=True)),
                ('study_school', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('km_home_work', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_description', models.TextField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('work_email', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrEmployeeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_employee_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expected_employees', models.IntegerField(blank=True, null=True)),
                ('no_of_employee', models.IntegerField(blank=True, null=True)),
                ('no_of_recruitment', models.IntegerField(blank=True, null=True)),
                ('no_of_hired_employee', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'hr_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrJobHrRecruitmentStageRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hr_job_hr_recruitment_stage_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrPlanActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_plan_activity_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrPlanHrPlanActivityTypeRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hr_plan_hr_plan_activity_type_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrPlanWizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_plan_wizard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrRecruitmentDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_recruitment_degree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrRecruitmentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_recruitment_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrRecruitmentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('fold', models.BooleanField(blank=True, null=True)),
                ('legend_blocked', models.CharField(max_length=100)),
                ('legend_done', models.CharField(max_length=100)),
                ('legend_normal', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_recruitment_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrCompanyPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('no_of_views', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'hr_company_plan',
            },
        ),
        migrations.CreateModel(
            name='HrCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=175)),
                ('limit_exceeded', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RRHH.HrCompanyPlan')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'hr_company',
            },
        ),
    ]
